### ISSUE TITLE
Full text search applies to named entities facet 

### ISSUE THREAD

**Issue by Julm** [ICIJ/datashare-client#9]
Full text search applies directly to named entities facet values. 
Instead, one would want the facet to display all named entities that are children of/extracted from/mentioned in documents matching the search query. 

When searching for a term T (in main search bar), named entities facet is updated exclusively with those named entities that contain T.

Issue related to https://github.com/ICIJ/datashare-client/issues/4#issue-358119823

**Comment by annelhote** [comment]
@Julm the related [issue](#4) is now fixed. Would you test in prod if it also fixed this issue ? I would say "Yes". Thank you.

**Comment by Julm** [comment]
Thnk you @annelhote!

It seems the issue is not fixed. 
I tested datashare.cloud.icij.org and DataShare 0.38 locally, freshly built from sources. 
Have I missed something? 

![screenshot from 2018-10-26 16-32-15](https://user-images.githubusercontent.com/2683717/47575463-717ebb80-d942-11e8-8def-e42722af0bac.png)

I'm attaching screenshots.
![screenshot from 2018-10-26 16-32-26](https://user-images.githubusercontent.com/2683717/47575458-717ebb80-d942-11e8-9627-270d53fbcc9d.png)

**Comment by annelhote** [comment]
To reproduce it :
1. On localhost, remove current index
`curl -XDELETE elasticsearch:9200/local-datashare`
2. Create file containing this text :
`This is an organzation : Tax Ltd.`
3. Create a second file containing this text :
`This is not an organzation : Tax. Create a location named entity : Texas.`
4. [Index](http://localhost:9090/#/indexing) these files and find named entities with IXAPIPE
5. If you look at the [results](http://localhost:9090/#/?q=%2a&size=25&sort=relevance), you should see 2 documents found in total, 1 named entity in Locations : "Texas" and one named entity in Organizations : "TAX LTD.".
6. If you [search for tax](http://localhost:9090/#/?q=tax&size=25&sort=relevance), you should see 2 documents found in total, 1 named entity in Locations : "Texas" and one named entity in Organizations : "TAX LTD." (same as 5.).

So the results listed in 6. in the 3 named entity facets, are in the same time all the named entities containing the query string, and all the named entities linked to a document containing the query string.

**Comment by annelhote** [comment]
Ok @Julm , it should be corrected on our prod server now. May let you test it ?
Thank you !

**Comment by Julm** [comment]
Thanks @annelhote. Solved!

**Comment by annelhote** [comment]
Thank to you @Julm. I close this issue.
